spring:
  data:
    redis:
      host: localhost
      port: 6379
      # 未配密码，单机演示用；生产环境务必配置
  ai:
    deepseek:
      base-url: https://api.deepseek.com
      api-key: '1111'
      chat:
        model: deepseek-chat  # 默认模型
        temperature: 0.7

    ollama:
      base-url: http://localhost:11434
      embedding:
        model: bge-m3

    vectorstore:
      milvus:
        client:
          host: localhost
          port: 19530
        database-name: default
        collection-name: react_rag
        embedding-dimension: 1024
        index-type: IVF_FLAT
        metric-type: COSINE
        initialize-schema: true

server:
  port: 8090
management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus